import datetime

dico_latitudes = {'Gif_sur_Yvette': 48.5, 'Le_Pin_aux_Haras': 48.7,
                  'Lelystad': 52.5, 'Le_Rheu': 48.1,
                  'Alenya': 42.6, 'Grignon': 48.8,
                  'Colmar': 48.1, 'Fagniere': 49, 'Clermont': 45.7,
                  "Nottingham": 52.9}

experiments = {
    "Sreten": {"sowing_date": datetime.date(1998, 10, 15), "year": "1999",
               "meteo": "Grignon",
               "location": "Grignon", "dist_inter_rang": 0.175,
               "genotype": ["Soissons"], "Ln_final": 11},
    "Rim1-1": {"sowing_date": datetime.date(2007, 9, 25), "year": "2008",
               "location": "Grignon", "meteo": "Grignon",
               "dist_inter_rang": 0.175,
               "genotype": ["Soissons"], "Ln_final": 11},
    "Rim1-2": {"sowing_date": datetime.date(2007, 11, 12), "year": "2008",
               "location": "Grignon", "meteo": "Grignon",
               "dist_inter_rang": 0.175,
               "genotype": ["Soissons"], "Ln_final": 11},
    "Rim2-1": {"sowing_date": datetime.date(2008, 9, 30), "year": "2009",
               "location": "Grignon", "meteo": "Grignon",
               "dist_inter_rang": 0.175,
               "genotype": ["Soissons"], "Ln_final": 11},
    "Rim2-2": {"sowing_date": datetime.date(2008, 11, 17), "year": "2009",
               "location": "Grignon", "meteo": "Grignon",
               "dist_inter_rang": 0.175,
               "genotype": ["Soissons"], "Ln_final": 11},
    "Jillian": {"sowing_date": datetime.date(2003, 10, 16), "year": "2004",
                "location": "Grignon", "meteo": "Grignon",
                "dist_inter_rang": 0.175,
                "genotype": ["Soissons"], "Ln_final": 11},
    "Jessica": {"sowing_date": datetime.date(2005, 10, 27), "year": "2006",
                "meteo": "Grignon", "location": "Grignon",
                "dist_inter_rang": 0.175,
                "genotype": ["Soissons"], "Ln_final": 11.3},
    "Mariem": {"sowing_date": datetime.date(2010, 10, 26), "year": "1901",
               "location": "Grignon", "meteo": "Grignon",
               "dist_inter_rang": 0.175,
               "genotype": ["Maxwell"], "Ln_final": 11.3},
    "Darwinkel": {"sowing_date": datetime.date(1976, 10, 19),
                  "year": "1977", "location": "Lelystad", "meteo": "Lelystad",
                  "dist_inter_rang": 0.175, "genotype": ["Lely"],
                  "Ln_final": 11},
    "Darwinkel_temp": {"sowing_date": datetime.date(2013, 10, 19),
                       "year": "1901", "location": "Grignon",
                       "meteo": "Grignon",
                       "dist_inter_rang": 0.175, "genotype": ["Maxwell"],
                       "Ln_final": 11},
    "Wheatamix-2014": {"sowing_date": datetime.date(2013, 10, 31),
                       "year": "2014", "location": "Grignon",
                       "meteo": "Grignon",
                       "dist_inter_rang": 0.175, "genotype": ["Soissons"],
                       "Ln_final": 11},
    "Ouitamics-2014": {"sowing_date": datetime.date(2013, 10, 30),
                       "year": "2014", "location": "Gif_sur_Yvette",
                       "meteo": "Gif_sur_Yvette",
                       "dist_inter_rang": 0.15,
                       "genotype": ["Soissons", "Apache", "Renan",
                                    "Caphorn", "A208", "A210", "F236",
                                    "A398"], "Ln_final": 11},
    "None": {"sowing_date": datetime.date(2013, 10, 15), "year": "2014",
             "location": "Gif_sur_Yvette", "meteo": "Gif_sur_Yvette",
             "dist_inter_rang": 0.1,
             "genotype": ["Soissons", "Maxwell"], "Ln_final": 11},
    "Mariem_mean": {"sowing_date": datetime.date(1900, 10, 26),
                    "year": "1901", "meteo": "Grignon_mean10",
                    "location": "Grignon",
                    "dist_inter_rang": 0.175, "genotype": ["Maxwell"],
                    "Ln_final": 11},
    "Darwinkel_Grignon_mean": {"sowing_date": datetime.date(1900, 10, 19),
                               "year": "1901", "meteo": "Grignon_mean10",
                               "location": "Grignon",
                               "genotype": ["Maxwell"], "Ln_final": 11},
    "Darwinkel_mean": {"sowing_date": datetime.date(1900, 10, 19),
                       "year": "1901", "meteo": "Lelystad_mean10",
                       "location": "Lelystad",
                       "dist_inter_rang": 0.175, "genotype": ["Maxwell"],
                       "Ln_final": 11.3
                       },
    "Sparkes_2001": {"sowing_date": datetime.date(2000, 10, 17),
                     "year": "2001", "location": "Nottingham",
                     "meteo": "Nottingham",
                     "dist_inter_rang": 0.135, "genotype": ["Maxwell"],
                     "Ln_final": 11},
    "Sparkes_2002": {"sowing_date": datetime.date(2001, 10, 4),
                     "year": "2002", "location": "Nottingham",
                     "meteo": "Nottingham",
                     "dist_inter_rang": 0.135, "genotype": ["Maxwell"],
                     "Ln_final": 11},
    "Sparkes_2003": {"sowing_date": datetime.date(2002, 9, 20),
                     "year": "2003", "location": "Nottingham",
                     "meteo": "Nottingham",
                     "dist_inter_rang": 0.135, "genotype": ["Maxwell"],
                     "Ln_final": 11},
    "Association": {"sowing_date": datetime.date(2013, 10, 30),
                    "year": "2014", "location": "Gif_sur_Yvette",
                    "meteo": "Gif_sur_Yvette",
                    "dist_inter_rang": 0.175,
                    "genotype": ["Gigant_Maxwell", "Darwinkel_Maxwell"],
                    "Ln_final": 11},
    "Sensitivity_Analysis": {"sowing_date": datetime.date(1900, 10, 15),
                             "year": "1901", "meteo": "Climat_moy_AS",
                             "location": "Grignon",
                             "dist_inter_rang": 0.175,
                             "genotype": ["Maxwell"], "Ln_final": 11.3},
}


def experimental_conditions(expe_related='Sensitivity_Analysis'):
    return experiments[expe_related]


def liste_expe():
    return experiments.keys()


def get_latitude(location):
    return dico_latitudes[location]
